baseURL = "http://clrcrl.com/"

[params]
    [[params.links]]
        icon = "github-square"
        title = "Github"
        url = "https://github.com/clrcrl"

    [[params.links]]
        icon = "linkedin"
        title = "LinkedIn"
        url = "https://linkedin.com/in/clrcrl"

    [[params.links]]
        iconset = "fas"
        icon = "envelope"
        title = "Email"
        url = "mailto:hello@clrcrl.com"
